export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

export const CREATE_MEETING = "CREATE_MEETING";
export const DELETE_MEETING = "DELETE_MEETING";
export const GET_ALL_MEETINGS = "GET_ALL_MEETINGS";
export const GET_MEETING = "GET_MEETING";
export const UPDATE_MEETING = "UPDATE_MEETING";
export const INVITE_TO_MEETING = "INVITE_TO_MEETING";

